#! /bin/sh
user=pi
x="`/usr/bin/getent passwd $user`" || echo "user $user not found"
if [ "$x" = "" ] ; then
    echo user pi not found
    exit 1
else
    echo "user pi already exists"
fi
homedir=`echo "$x" |cut -f 6 -d :`
if [ ! -d "$homedir" ] ; then
    echo "home directory $homedir not found, creating it for logs"
    mkdir -p "$homedir"
    chown -R $user "$homedir"
fi

systemctl daemon-reload
systemctl enable --now opwebmain
